'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root=path.resolve(__dirname,'../../..');
const app=require(path.join(root,'tools/sp/round_c/app.js'));
const product=JSON.parse(fs.readFileSync(path.join(root,'sp/deputados-federais/dados.json'),'utf8'));
const cards=product.records.map(c=>({party:c.party,status:c.status_id,search:app.fold(`${c.name} ${c.official_name} ${c.full_name} ${c.number} ${c.party}`),topics:c.themes_2026.map(x=>x.id)}));
const valid={parties:product.party_scope,topics:product.taxonomy.map(x=>x.id),statuses:[...new Set(cards.map(c=>c.status))]};
const read=q=>app.parseState(q,valid);
const count=q=>cards.filter(c=>app.matches(c,read(q))).length;
test('accent-insensitive query and exact identity',()=>{assert.equal(count('?q=samia'),1);assert.equal(count('?q=SÂMIA%205000'),1);assert.equal(count('?q=5000%20PT'),0);});
test('default includes every electoral status and all 249',()=>assert.equal(count(''),249));
test('new canonical parties and zero PCB',()=>{assert.equal(count('?partidos=REDE'),10);assert.equal(count('?partidos=PSTU'),5);assert.equal(count('?partidos=PCB'),0);});
test('selected parties are OR, never party-based topic inference',()=>{assert.equal(count('?partidos=PT,PSOL'),85);assert.equal(count('?partidos=REDE&pautas=educacao'),0);});
test('education and water counts follow canonical evidence',()=>{assert.equal(count('?pautas=educacao'),20);assert.equal(count('?pautas=agua-saneamento'),8);});
test('all-topic set is an intersection; any-topic set is a union',()=>{const a=new Set(cards.filter(c=>c.topics.includes('saude')));const b=new Set(cards.filter(c=>c.topics.includes('educacao')));assert.equal(count('?pautas=saude,educacao'),new Set([...a,...b]).size);assert.equal(count('?pautas=saude,educacao&modo=todos'),[...a].filter(c=>b.has(c)).length);});
test('search, status, parties and topics combine conjunctively',()=>{assert.equal(count('?q=samia&partidos=PSOL&pautas=saude&modo=todos&situacao=deferido'),1);assert.equal(count('?q=samia&partidos=PT&pautas=saude'),0);});
test('renunciations retained and filterable',()=>assert.equal(count('?situacao=renuncia'),6));
test('unknown URL options discarded safely with notice',()=>{const s=read('?partidos=XYZ,PT&pautas=evil&situacao=nope');assert.deepEqual(s.parties,['PT']);assert.deepEqual(s.topics,[]);assert.equal(s.status,'');assert.equal(s.ignored.length,3);});
test('old topic IDs migrated explicitly',()=>{assert.deepEqual(read('?pautas=apostas-protecao-economica').topics,['apostas-jogos']);assert.deepEqual(read('?pautas=infraestrutura-desenvolvimento-regional').topics,['infraestrutura-desenvolvimento']);assert.deepEqual(read('?pautas=povos-indigenas-comunidades-tradicionais').topics,['povos-indigenas-tradicionais']);});
test('duplicate selections deduplicated and party case canonicalized',()=>{assert.deepEqual(read('?partidos=pt,PT,pcdob').parties,['PCdoB','PT']);assert.deepEqual(read('?pautas=saude,saude').topics,['saude']);});
test('shareable serialization is deterministic and reversible',()=>{const s=read('?q=São%20Paulo&partidos=PT,PSOL&pautas=saude,educacao&modo=todos&ordem=alfabetica&situacao=deferido');assert.deepEqual(read(app.serializeState(s)),s);assert.equal(app.serializeState(read('')), '');});
test('user text stays text and has bounded length',()=>{assert.equal(read('?q='+encodeURIComponent('<script>alert(1)</script>')).q,'<script>alert(1)</script>');assert.equal(read('?q='+'x'.repeat(300)).q.length,140);});
test('Brazilian daily key respects midnight boundary',()=>{assert.equal(app.dayKey(new Date('2026-09-22T02:59:59Z')),'2026-09-21');assert.equal(app.dayKey(new Date('2026-09-22T03:00:00Z')),'2026-09-22');});
test('daily rotation preserves every item and is not a score',()=>{const a=['A','B','C','D'];const r=app.rotate(a,'2026-09-21');assert.deepEqual([...r].sort(),a);assert.deepEqual(a,['A','B','C','D']);assert.notDeepEqual(r,app.rotate(a,'2026-09-22'));assert.deepEqual(app.rotate([],'2026-09-21'),[]);});
test('history-only and undated claims never enable current filters',()=>{for(const c of product.records.filter(x=>x.claims_other.length&&!x.claims_2026.length)){assert.deepEqual(c.themes_2026,[]);}assert.equal(product.records.filter(x=>x.claims_other.length&&!x.claims_2026.length).length,6);});
